server:
  port: 9002

spring:
  application:
    name: ihrm-system
  datasource:
    url: jdbc:mysql://localhost:3306/ihrm?useSSL=false&useUnicode=true&characterEncoding=utf-8&characterSetResults=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

jwt:
  config:
    key: saas-ihrm
    ttl: 360000